### ISSUE TITLE
What is the licence for this work?

### ISSUE THREAD

**Issue by loicbenoit** [pchen66/pchen66.github.io#2]
Are we allowed to re-use and modify your Panolens example projects? What licence applies? How do you suggest providing attribution to you as the original creator of the work?

Panolens is exactly what my client is looking for. It would be used in a commercial project.

**Comment by pchen66** [comment]
Yes, it's under MIT license so it's free of charge for modification and commercial use. Here's the [license](https://github.com/pchen66/panolens.js/blob/master/LICENSE). As for original author, you can simply put [Ray Chen](http://pojuichen.com). :)
