### ISSUE TITLE
fullscreen function

### ISSUE THREAD

**Issue by ridho-satria-magnus** [pchen66/pchen66.github.io#3]
Is there a function to set container to fullscreen.
I got viewer.widget.fullscreenElement.click() and doesn't work on mobile device

**Comment by pchen66** [comment]
Are you using iOS? If so, it doesn't support fullscreen API [API Support Table](https://caniuse.com/#feat=fullscreen)
Panolens already checks if your browser has fullscreen API support and displays `fullscreenElement` only when it's supported. If you use an Android device to take a look, you will see the option pops up.
