### ISSUE TITLE
IOS FullScreen Problems

### ISSUE THREAD

**Issue by Wulff2099** [pchen66/pchen66.github.io#6]
In the panorama "loading_progress.html" Page
When i want to go to fullscreen in the iphone i cant
I notice it happes with some other pages.
If somebody know how to fix this i will be happy

**Comment by pchen66** [comment]
Fullscreen button only appears only when the device has Fullscreen API support. iOS on iPhone doesn't support HTML5 Fullscreen API, however, according to [caniuse](https://caniuse.com/#feat=fullscreen) iPad does support. So, we have to rely on Apple to support this feature.

![Screen Shot 2019-05-17 at 10 00 16 AM](https://user-images.githubusercontent.com/2421225/57944068-a4f74800-788a-11e9-9f7b-584ffa3cb5ff.png)
